server.port=${PORT:${CUSTOMER_PORT:8020}}
server.servlet.context-path=/shop

#datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the
# chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
# here ddl-auto setting to none, because I have backed up db
# backup, (For Docker use)
spring.jpa.hibernate.ddl-auto = none

# ================= RAZORPAY =================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# ================= JWT =================
jwt.secret=${CUSTOMER_JWT_SECRET}
jwt.expiration=86400000

# To send mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#multipart-file
spring.servlet.multipart.enabled= true
spring.servlet.multipart.file-size-threshold = 2KB
spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size= 100MB

# produces json
spring.mvc.produces-json=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

management.endpoints.web.exposure.include=health,info,metrics,httptrace
management.endpoint.health.show-details=always







